import { Router, type IRouter } from "express";

const router: IRouter = Router();

const NEWS_ARTICLES = [
  { id: 1, title: "Kharif 2026 Sowing Season Starts with Record Rainfall", description: "India's kharif sowing season has begun on a positive note with above-normal rainfall across Maharashtra, Karnataka, and Andhra Pradesh. Farmers are urged to take advantage of the moisture and sow early.", source: "Agri Tribune", date: "2026-03-10", category: "news", imageUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=400", url: "#" },
  { id: 2, title: "New High-Yield Rice Variety Released by ICAR", description: "ICAR has released a new rice variety CR Dhan 801 that gives 20% higher yield compared to conventional varieties. The variety is resistant to bacterial blight and blast disease.", source: "Krishi Jagran", date: "2026-03-08", category: "news", imageUrl: "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=400", url: "#" },
  { id: 3, title: "Drone Technology Transforms Pesticide Application in India", description: "Agri-drones are now being used across 500,000 hectares in India for precision pesticide application, reducing chemical use by 30% while improving effectiveness and reducing farmer exposure.", source: "Modern Agriculture", date: "2026-03-06", category: "news", imageUrl: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?w=400", url: "#" },
  { id: 4, title: "Soil Health Cards Help Farmers Cut Fertilizer Costs by 25%", description: "Farmers who followed Soil Health Card recommendations for targeted fertilization reported an average 25% reduction in fertilizer expenditure while maintaining crop yields.", source: "Agriculture Today", date: "2026-03-04", category: "news", imageUrl: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400", url: "#" },
  { id: 5, title: "eNAM Platform Crosses 1 Crore Farmer Registration Mark", description: "The Electronic National Agriculture Market (eNAM) platform has crossed 1 crore farmer registrations, enabling direct farm-to-market price discovery and reducing middlemen margins.", source: "Economic Times Agri", date: "2026-03-02", category: "news", imageUrl: "https://images.unsplash.com/photo-1542601906897-eef0c57d490e?w=400", url: "#" },
  { id: 6, title: "Organic Farming Area Increases by 40% in Last 5 Years", description: "India's certified organic farming area has grown from 4.7 million hectares to 6.6 million hectares, making India the world's largest organic producer by number of farmers.", source: "Organic Farmer", date: "2026-02-28", category: "news", imageUrl: "https://images.unsplash.com/photo-1500651230702-0e2d8a49d4ad?w=400", url: "#" },
  { id: 7, title: "PM Modi Announces ₹50,000 Crore Farm Irrigation Fund", description: "Prime Minister announced a major irrigation fund under Pradhan Mantri Krishi Sinchayee Yojana to provide micro-irrigation to 2 crore additional farmers over the next 3 years.", source: "India Today", date: "2026-02-25", category: "news", imageUrl: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=400", url: "#" },
  { id: 8, title: "Tomato Price Crash: Government Procures 5 Lakh Tonnes for Processing", description: "Following a sharp decline in tomato prices due to bumper production, the government has intervened to procure 5 lakh tonnes for ketchup and tomato paste processing units.", source: "The Hindu Business Line", date: "2026-02-22", category: "news", imageUrl: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=400", url: "#" },
];

const GOVERNMENT_SCHEMES = [
  { id: 1, name: "PM Kisan Samman Nidhi", description: "Direct income support of ₹6,000 per year to all landholding farmer families across India, provided in 3 equal installments of ₹2,000 each.", benefit: "₹6,000/year direct benefit transfer", eligibility: "All small and marginal farmers with cultivable land", applicationUrl: "https://pmkisan.gov.in", ministry: "Ministry of Agriculture", category: "Income Support" },
  { id: 2, name: "PM Fasal Bima Yojana", description: "Comprehensive crop insurance scheme that provides financial support to farmers suffering crop loss/damage due to unforeseen events like natural calamities, pests and diseases.", benefit: "Crop insurance at 1.5% (Rabi), 2% (Kharif) premium", eligibility: "All farmers growing notified crops in notified areas", applicationUrl: "https://pmfby.gov.in", ministry: "Ministry of Agriculture", category: "Crop Insurance" },
  { id: 3, name: "Soil Health Card Scheme", description: "Provides farmers information about soil nutrient status and fertilizer recommendations for 12 parameters to help them improve productivity with less input costs.", benefit: "Free soil testing and crop-wise recommendations", eligibility: "All farmers across India", applicationUrl: "https://soilhealth.dac.gov.in", ministry: "Ministry of Agriculture", category: "Soil Health" },
  { id: 4, name: "Kisan Credit Card (KCC)", description: "Provides farmers with affordable credit for agricultural needs including crop cultivation, post-harvest expenses, produce marketing and ancillary activities.", benefit: "Credit limit up to ₹3 lakh at 4% interest rate", eligibility: "All farmers, sharecroppers, oral lessees, self-help groups", applicationUrl: "https://agriculture.gov.in/kcc", ministry: "Ministry of Finance/Agriculture", category: "Credit" },
  { id: 5, name: "eNAM (Electronic National Agriculture Market)", description: "Pan-India online trading platform for agricultural commodities, facilitating price discovery and reducing post-harvest losses by connecting farmers to more buyers.", benefit: "Direct market access, better price discovery", eligibility: "All farmers and traders registered in mandis", applicationUrl: "https://enam.gov.in", ministry: "Ministry of Agriculture", category: "Marketing" },
  { id: 6, name: "Pradhan Mantri Krishi Sinchayee Yojana", description: "Ensures water supply to every farm and promotes water use efficiency through micro-irrigation and watershed development.", benefit: "55% subsidy on drip/sprinkler irrigation for small farmers", eligibility: "Small and marginal farmers (up to 5 acres)", applicationUrl: "https://pmksy.gov.in", ministry: "Ministry of Agriculture", category: "Irrigation" },
  { id: 7, name: "National Horticulture Mission", description: "Promotes holistic growth of horticulture sector including area expansion, post-harvest management and processing.", benefit: "50% subsidy on horticulture equipment and cold storage", eligibility: "Horticulture farmers and FPOs", applicationUrl: "https://nhb.gov.in", ministry: "Ministry of Agriculture", category: "Horticulture" },
  { id: 8, name: "Paramparagat Krishi Vikas Yojana", description: "Promotes organic farming through cluster approach, includes free inputs, certification and marketing support for organic farmers.", benefit: "₹50,000/hectare over 3 years for organic farming", eligibility: "Farmers interested in organic farming certification", applicationUrl: "https://pgsindia-ncof.gov.in", ministry: "Ministry of Agriculture", category: "Organic Farming" },
];

router.get("/news", (_req, res) => {
  res.json({ news: NEWS_ARTICLES, schemes: GOVERNMENT_SCHEMES });
});

export default router;
